#!/usr/bin/env bash

# Periodically clean up the remote backup only, we are making more frequent backups locally to SD card
# and will prune immediately after backup
source $HOME/.restic.env

restic -r b2:mockingbird-backup:/restic/tanq/repo forget --keep-daily 7 --keep-weekly 4 --keep-monthly 12 --prune
